### PR TITLE
[deps] change requests-cache submodule URL #1748

### PR DESCRIPTION
**Pull request by midichef**
to allow `pip install git+https://github.com/saulpw/visidata@develop`

### CODE REVIEW

**Comment by anjakefala** [comment]
Thanks so much! I was wondering about that.

**Comment by anjakefala** [comment]
(Tangentially, I do not think you need `@develop` anymore, bc now `develop` is the main branch on github.)

**Comment by midichef** [comment]
Oh, that's good to know. Thanks for solving this!

**Comment by anjakefala** [comment]
Haha, the typo was bc I originally set up the submodule with the `https` url, then realised that Saul originally set the url as `git@`, and questioned myself. Do not sleepily commit, friends.

**Pull request merged**
