### PR TITLE
[pandas] Include DataFrame index by moving to columns

### PR DESCRIPTION
**Pull request by danlat**
Visidata is awesome for doing some quick browsing of parquet files using pandas, but wasn't including the index. This adds the index as long as it's not the default RangeIndex (0-n)

### CODE REVIEW

**Review by saulpw — COMMENTED** [review]
Thanks for this PR, @danlat.  If we make a new DF, will edits or other changes be propagated back to the origina DF?  (i.e. should this have inplace=True?)  Also @azjps, does this interact with your changes at all?

**Comment by danlat** [comment]
The original DF will be gone and self.df will reference our new one with the index reset to columns.

**Comment by anjakefala** [comment]
Hi @danlat! Would you mind opening this PR again on the `develop` branch? See [here](https://github.com/saulpw/visidata/blob/develop/CONTRIBUTING.md#submitting-code). Once you do, I think this looks good.

**Comment by azjps** [comment]
> Thanks for this PR, @danlat. If we make a new DF, will edits or other changes be propagated back to the origina DF? (i.e. should this have inplace=True?) Also @azjps, does this interact with your changes at all?

@saulpw no, it won't be conflict with my PR. I do think maybe there could be an option somewhere to toggle what to do with the index -- as you mentioned it could cause some confusion with any editing features, and another possibility which is probably most aesthetically appropriate is to set the index columns as keys.

**Comment by anjakefala** [comment]
@azjps
```
as you mentioned it could cause some confusion with any editing features
```
Thanks for drawing my attention to this.

```
another possibility which is probably most aesthetically appropriate is to set the index columns as keys.
```
:purple_heart:

**Pull request closed without merging**
