### PR TITLE
[statusbar-] use '' for BaseSheet selectedStatus

### LINKED ISSUE #2599: VisiData showing `{sheet.selectedStatus}` in right corner
image

Sometimes VisiData shows `{sheet.selectedStatus}` in the bottom right corner. This happens even without `.visidatarc`. I got it to happen when I drew a plot, though it might have been happening in non-plot sheets too.

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)? **Yes**

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)? **Both latest release and develop branch**

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)? **WSL Ubuntu on Windows, though I think it happens in normal Ubuntu too.**

- Which version of Python? **3.10.12**

- Which terminal are you using (for display and input issues)? **Windows Terminal, zsh.**

### PR DESCRIPTION
**Pull request by midichef**
Closes #2599.

'{selectedStatus}' appears in the `GraphSheet` statusbar as a raw string instead of a value. That's because `selectedStatus` can't be evaluated for `BaseSheet`.

### CODE REVIEW

**Comment by saulpw** [comment]
Once upon a time the graph sheet reflected the selection on the source sheet (see the unused `color_graph_selected` and other remnants).  I believe it's still possible to select/unselect elements this way, but the selection itself is invisible.  (I'd love to get that working again, but that's outside the scope of this PR.)

**Review by saulpw — COMMENTED** [review]
I edited the PR to add a separate BaseSheet.property for `selectedStatus` that returns an empty string.  OOP overloading instead of duck-typing.  Note that this is untested code (though I don't see how it wouldn't work..)

**Comment by anjakefala** [comment]
Upon reproducing, this came up:

```
Traceback (most recent call last):
  File "/home/anja/git/visidata/visidata/sidebar.py", line 115, in drawSidebar
    sidebar, title = sheet.help_sidebars[vd.disp_help%len(sheet.help_sidebars)]()
                                         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: integer modulo by zero

```

**Comment by anjakefala** [comment]
Ah, this is unrelated! I will open an issue and investigate this separately. The core issue has been resolved.

**Pull request merged**
