### PR TITLE
New core loader: vnlog

### PR DESCRIPTION
**Pull request by dkogan**
Hi. This is a new core loader for the vnlog format: https://github.com/dkogan/vnlog

Basic reading/writing works. I followed the contributing checklist best I could. The section about tests is unclear, so I didn't do that. If you clarify, I can do the thing. There are a number of other things the checklist should have. Let me know if you want a separate issue for those.

### CODE REVIEW

**Comment by saulpw** [comment]
Hey @dkogan, thanks for putting this together.  I think this is a perfect candidate for a plugin, which could just live in the dkogan/vnlog repo itself. https://www.visidata.org/docs/contributing/#plugins.

 I'll close this PR now and you can submit another one (against `develop` branch) to add a line into [plugins.jsonl](https://github.com/saulpw/visidata/blob/develop/plugins/plugins.jsonl), with a link to the `dkogan/vnlog` repo.

Also, what other things should the checklist have, in your opinion?

**Comment by dkogan** [comment]
Hi. Notes inline.

Saul Pwanson ***@***.***> writes:

> I think this is a perfect candidate for a plugin, which could just
> live in the dkogan/vnlog repo itself.

Let me think about this... So the code would live in my repo, while your
repo has a hash... This can't work. As I understand it, the big
advantage of the split code, is that the two sides can move
independently, and I can fix bugs without hassling you. And you don't
need to be maintaining my code. But if you hold a hash of my contents,
then I can't touch my code without also touching your repo.

When this is installed as packages, I could have visidata version 1.2.3
installed. Then I can also have vnlog-visidata-plugin version whatever
installed, which Depends:visidata=1.2.3. Because of the hash, this has
to be "=", not "<" or ">" or anything else. And then, as the maintainer
of vnlog-visidata-plugin I cannot upload any updates to my package,
since I'm not also the maintainer of the visidata package, and that
maintainer has their own schedule. I don't see any packages in Debian
currently that ship visidata plugins, so I don't think anybody has
encountered this yet. But if visidata becomes more popular, you'll hear
complaints about it.

Are you SURE you want to be doing things this way? It sounds like you're
trying to reimplement package management; partially. I think you should
drop the hash requirement, or accept more formats into the core. Or you
can have some sort of "visidata API version", and the dependencies will
have to match that.


> Also, what other things should the checklist have, in your opinion?

Looking back at it, maybe I was interpreting the "checklist" as more of
a "recipe", and in that context it was a bit sparse. My bad maybe. I
still think it would be nice either to provide more detail in the
checklist, or to add html links to the relevant sections in the
documentation.

To make it more clear, it'd be nice to say where the "open_foo" function
should live (presumably in foo.py). And then it would say to import
foo.py in __init__.py. The "# rowdef" comment line needs more
explanation, so link to the docs would be really nice. Also, the
location of the "# rowdef" comment in the various existing source files
isn't 100% consistent, and making it consistent would unambiguously
suggest how to do that properly.

The test stuff, I don't grok, so maybe it's complete, I just don't quite
understand. It says to add "load-foo.vd to tests/". Looking at what's
already there, it looks like they're all tsv. So I should convert my
sample to tsv, and store that into load-foo.vd? It then talks about
"replaying vd load-foo.vd", to save it as tsv into tests/golden? But
isn't load-foo.vd already a tsv? Am I saving the same thing into
tests/golden?

I tried to figure it out by running the test suite to see what it did
for sqlite, but it did this:


  ***@***.***:~/projects/visidata$ PYTHONPATH=$PWD ./setup.py test
  running test
  WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
  running egg_info
  writing visidata.egg-info/PKG-INFO
  writing dependency_links to visidata.egg-info/dependency_links.txt
  writing entry points to visidata.egg-info/entry_points.txt
  writing requirements to visidata.egg-info/requires.txt
  writing top-level names to visidata.egg-info/top_level.txt
  file visidata.py (for module visidata) not found
  reading manifest file 'visidata.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'visidata.egg-info/SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "/home/dima/projects/visidata/./setup.py", line 8, in <module>
      setup(name='visidata',
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 232, in run
      self.run_tests()
    File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 250, in run_tests
      test = unittest.main(
    File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
      self.parseArgs(argv)
    File "/usr/lib/python3.9/unittest/main.py", line 124, in parseArgs
      self._do_discovery(argv[2:])
    File "/usr/lib/python3.9/unittest/main.py", line 244, in _do_discovery
      self.createTests(from_discovery=True, Loader=Loader)
    File "/usr/lib/python3.9/unittest/main.py", line 154, in createTests
      self.test = loader.discover(self.start, self.pattern, self.top)
    File "/usr/lib/python3.9/unittest/loader.py", line 349, in discover
      tests = list(self._find_tests(start_dir, pattern))
    File "/usr/lib/python3.9/unittest/loader.py", line 405, in _find_tests
      tests, should_recurse = self._find_test_path(
    File "/usr/lib/python3.9/unittest/loader.py", line 483, in _find_test_path
      tests = self.loadTestsFromModule(package, pattern=pattern)
    File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
      tests.append(self.loadTestsFromName(submodule))
    File "/usr/lib/python3.9/unittest/loader.py", line 205, in loadTestsFromName
      test = obj()
  TypeError: urlcache() missing 1 required positional argument: 'url'


This wasn't meant to be quite so long. Sorry.

**Comment by saulpw** [comment]
plugins.jsonl is in the visidata repo, but that's just its current resting place, as it's hosted on visidata.org.  We don't release a new version of VisiData whenever a plugin gets updated, but merely copy the update plugins.jsonl to the website.  The hash is to make sure that the code people are installing is the same code that we've reviewed.  Otherwise a devious plugin author could release an innocent plugin and update it later with nefarious code and it would seem like we had vetted and approved it.

**Comment by dkogan** [comment]
Hi. Thanks for replying. So when is the hash checked? I can upload a new plugin to Debian, the hash won't match, and nothing will complain. Which maybe is OK, since we Debian people are so trustworthy :) Is the hash checked during a pip install?

I'm going to do the plugin pull request in the near future. Can you do the review you mentioned before I do that? I can imagine that I messed up some of the visidata bits. Thanks.

**Comment by saulpw** [comment]
The hash is checked when installed via VisiData.  You can work around it by manually putting the `import plugins.foo` into .visidatarc.

Do you have time to schedule a videochat during my ['office hours'](https://calendly.com/saulpw/visidata-office-hours?month=2021-08)?  I can review async but it's probably going to be faster/easier to talk through things sync.

**Comment by dkogan** [comment]
Saul Pwanson ***@***.***> writes:

> The hash is checked when installed via VisiData. You can work around
> it by manually putting the `import plugins.foo` into .visidatarc.

OK. I'll try it out


> Do you have time to schedule a videochat during my 'office hours'? I
> can review async but it's probably going to be faster/easier to talk
> through things sync.

These coming two weeks are bad, but I can do a not-too-long phone call
probably. When are the 'office hours'?

**Comment by saulpw** [comment]
You can click the link to schedule office hours.

**Comment by dkogan** [comment]
Saul Pwanson ***@***.***> writes:

> You can click the link to schedule office hours.

OK. FYI, github doesn't include html in their emails, so I didn't see a
link. I see it now, and I can't do any of those times in the next two
weeks. Can we do this asynchronously? There isn't all that much code to
look through, so hopefully this wouldn't be too terrible. Thanks.

**Comment by dkogan** [comment]
OK, I'm looking at this again. What do I need to ship in my packages to cause the installed visidata package pick up my plugin? Debian packages can add new files, but cannot modify existing files. The docs (https://www.visidata.org/docs/plugins/) only talk about user-local plugins, while a package would install into the system

**Comment by saulpw** [comment]
Can you install a stub or symlink into ~/.visidata/plugins that imports your plugin?

**Comment by dkogan** [comment]
Saul Pwanson ***@***.***> writes:

> Can you install a stub or symlink into ~/.visidata/plugins that
> imports your plugin?

Hi. I'm planning on doing a new release of vnlog shortly, with the
accompanying Debian upload. The user should be able to

  apt install visidata-plugin-vnlog

and then they should be able to

  vd whatever.vnl

I don't want to require them to touch ~/anything. This is the standard
expectation, since that's how all other tools work.

Thanks

**Comment by saulpw** [comment]
Hi @dkogan, I agree, that would be nice, but it's unfortunately not how the VisiData plugin system was designed.  We'll try to accommodate this use case when we update the plugin architecture in the future.

**Comment by dkogan** [comment]
Thanks for replying. I think I'm going to hold off on including this
plugin in my release for now. If you're planning an eventual update that
will make this possible, can you ping this bug? Or is there an open
issue somewhere already that I can subscribe to?

Thanks

**Pull request closed without merging**
