### PR TITLE
Support for MySQL

### PR DESCRIPTION
**Pull request by p3k**
From the experience I gained making the Postgres loader work again in v2 I decided to give a try to create a MySQL loader. Without further ado, here it is.

### CODE REVIEW

**Comment by p3k** [comment]
Hi again @anjakefala and @saulpw – is this something you would be interested in to include in v2?

**Comment by anjakefala** [comment]
Hi @p3k! 

I am charmed by your enthusiasm. =D

I have a favour to ask before we begin reviewing. 

The commits are a bit confusing to parse because you made your branch off the `stable` branch instead of the `develop` branch. Would you mind re-opening this PR branching off of `develop`?

I am always excited for adding loaders. We will probably ask you to contribute this as a plugin, and to take ownership of its upkeep/bugs (@saulpw decides which loaders are plugins, and which are part of core). We will talk through that once you re-open things.

**Comment by p3k** [comment]
> The commits are a bit confusing to parse because you made your branch off the `stable` branch instead of the `develop` branch. Would you mind re-opening this PR branching off of `develop`?

Ah, yes. I already wondered what I did wrong. Will do, please stay tuned.

> I am always excited for adding loaders. We will probably ask you to contribute this as a plugin, and to take ownership of its upkeep/bugs (@saulpw decides which loaders are plugins, and which are part of core). We will talk through that once you re-open things.

Alright, sounds reasonable.

**Comment by p3k** [comment]
@anjakefala Here is my second attempt: #617

**Pull request closed without merging**
