### PR TITLE
I'm aborruso, not aburroso :)

### PR DESCRIPTION
**Pull request by aborruso**
And I have added also a note, because if it's true, I'm proud of if (https://github.com/saulpw/visidata/issues/216#issuecomment-443627048)

### CODE REVIEW

**Comment by anjakefala** [comment]
Ahhhhhhhhh thank you!!

**Comment by aborruso** [comment]
@anjakefala I do not know if I'm right, but probably there is to add this new feature https://github.com/saulpw/visidata/issues/220

Am I wrong?

**Comment by anjakefala** [comment]
Oh, funny, you know how I missed that? I very rarely contribute code to visidata itself. This contribution was one of my early attempts at getting started with that.

So when I am parsing git logs to move stuff to CONTRIBUTING.md, I skip over my commits. ^^; They are primarily docs and test related.

Nice catch! Thank you thank you. 🎉  I will add it ASAP. =)

**Comment by anjakefala** [comment]
Added here: https://github.com/saulpw/visidata/commit/f98924510dc3f448371253c7f33c68bf762c690a

We should hopefully be good to go now. =D

**Pull request merged**
