### PR TITLE
Fixes for MySQL Loader

### PR DESCRIPTION
**Pull request by p3k**
Unfortunately, I just saw I made a syntax error in the `requirements.txt` file (single instead of double equal sign).

Furthermore, when trying to install `mysqlclient` on a machine without a MySQL / MariaDB installation present, I get the following error:

```plain
     command: /root/.virtualenvs/visidata/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vnuyv69l/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vnuyv69l/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dhjhy7fy
         cwd: /tmp/pip-install-vnuyv69l/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vnuyv69l/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-vnuyv69l/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-vnuyv69l/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

At least on the system I used (Ubuntu 18.04.4 LTS) I could fix this installing `libmysqlclient-dev` ([Source](https://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface)):

```sh
apt-get install libmysqlclient-dev
```

For now I added a FIXME comment to the `requirements.txt` file – please let me know if there is a better way to communicate this @saulpw

### CODE REVIEW

**Comment by saulpw** [comment]
Let's remove it from requirements.txt completely, and document this elsewhere.  Would you write up a short post on how to setup and use VisiData with a mysql db?  We can find a place to post it on visidata.org.

**Comment by saulpw** [comment]
I'll just remove it now so now one has a problem installing it.

**Comment by p3k** [comment]
> Would you write up a short post on how to setup and use VisiData with a mysql db? We can find a place to post it on visidata.org.

sorry for the long delay @saulpw, i did not forget this – here is the first draft: https://github.com/saulpw/visidata/wiki/Using-VisiData-with-MySQL-and-MariaDB

how are you handling images in the wiki or on visidata.org? i could provide two screenshot from the information schema if you think this is worthwhile.

what else could be missing?

**Comment by anjakefala** [comment]
Hi @p3k!

That was a great place to put it. I looked up how people add images to wikis, and got [this tutorial](https://docs.github.com/en/github/building-a-strong-community/editing-wiki-content#adding-images). Does that tutorial help?

For adding to the website, we have a page [/formats](https://www.visidata.org/formats/). I think that would be the best place for this information. I already added a section for MySQL, and you can add a notes section.

If you place your images in the [static folder](https://github.com/saulpw/visidata.org/tree/master/static), they will end up at the root when the website builds.

e.g. visidata.org/cool-graph.png

I am not sure if they are worthwhile, but since you already made them it would be cool for you to add them, so I could see them, and then we can remove them if they are not helpful!

Thanks so much. :blush:

**Comment by p3k** [comment]
thanks for your reply @anjakefala 

> I am not sure if they are worthwhile, but since you already made them it would be cool for you to add them, so I could see them, and then we can remove them if they are not helpful!

as the formats page does not contain any images i’d prefer to stick with the herd and only include the information from the wiki page in a condensed way, hopefully consistent with the rest of the notes – see https://github.com/saulpw/visidata.org/pull/37.

**Pull request closed without merging**
