### PR TITLE
Pw24 msgpack

### PR DESCRIPTION
**Pull request by maxim-uvarov**
- If contributing a core loader, refer to [the loader checklist](https://visidata.org/docs/contributing#loader).

I used the JSON dataset `sample_data/y77d-th95.json.gz` to create msgpack and msgpackz sample files.

I don't know how to do the following:
```
-   Set an appropriate `rowtype` string.
-   Provide a `# rowdef:` comment. This describes the structure of a row (e.g. its base class) in a **Sheet**.
-   If the loader's dependencies are not part of Python3 stdlib, note the additional dependencies in the `requirements.txt` (include a comment adjacent to the dep with the name of the loader).
```

I hope I haven't messed anything up.

Guys, please check 🙏

### CODE REVIEW

**Comment by maxim-uvarov** [comment]
related to #2419

**Comment by saulpw** [comment]
Don't worry about the first two, we are inheriting from JsonSheet so rowdef/rowtype are the same.  As for the deps,  just add the correct versions of msgpack and brotli to dependencies.txt.

Also, can you include the exact commands here that you used to create the sample data files?

Thanks for your help!

**Comment by maxim-uvarov** [comment]
@saulpw thank you for such a quick response and everything else!

I used nushell for creating sample files:

```nu
open y77d-th95.json | save y77d-th95.msgpack
open y77d-th95.json | to msgpackz --quality 2 | save -r y77d-th95.msgpackz
```

Do I need to use vd? 
Should I add a test for saving in msgpack format?

**Comment by maxim-uvarov** [comment]
i see that there is a problem with test files :( 
I'm checking everything

**Comment by saulpw** [comment]
This is great, thank you.  The PR as it is won't save msgpack formats yet.  Saving is often a bit more difficult, but if you can make a Python snippet that converts JSON(L) to a msgpack file, we can add that here too.  Otherwise we can merge only the loader and postpone the saver until later.

**Comment by maxim-uvarov** [comment]
@saulpw, tests run now fine. 

>  Saving is often a bit more difficult, but if you can make a Python snippet that converts JSON(L) to a msgpack file, we can add that here too. Otherwise we can merge only the loader and postpone the saver until later.

Let's merge it, please. 🙏 

Interacting with Python is stressful for me. Even though I'm really sad that I'm missing the opportunity to learn from your talent by avoiding learning Python, I just have too many projects happening and don't want to add more load.

**Review by saulpw — APPROVED** [review]
@anjakefala Please kick the tires on this and then we can merge it.

**Comment by anjakefala** [comment]
@maxim-uvarov Does loading the msgpackz file work for you locally?

I'm running into the following error, and looking into it:

```
  File "/home/anja/git/visidata/visidata/sheets.py", line 276, in reload
    self.loader()
  File "/home/anja/git/visidata/visidata/sheets.py", line 301, in loader
    for r in self.iterload():
  File "/home/anja/git/visidata/visidata/loaders/msgpack.py", line 19, in iterload
    yield from msgpack.unpackb(data, raw=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

```

**Comment by maxim-uvarov** [comment]
Hello dears!

I merged the latest commits from @anjakefala. I installed visidata with `pip install .` I opened `zsh`, I used the commands below inside the `sample_data` directory.
```
> git log -1
```
```
commit 3c17fdc84126e2b3977e8e2fec80149577373e81 (HEAD -> pw24_msgpack, origin/pw24_msgpack)
Author: anjakefala <anja.kefala@gmail.com>
Date:   Tue Jun 11 22:10:02 2024 -0700


    Fix load-msgpackz
```

this works ok:
```
> vd test.msgpack 
```

this doesn't work
```
> vd test.msgpackz
```

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/threads.py", line 227, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/sheets.py", line 276, in reload
    self.loader()
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/sheets.py", line 301, in loader
    for r in self.iterload():
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/loaders/msgpack.py", line 19, in iterload
    yield from msgpack.unpackb(data, raw=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

this doesn't work:
```
> cat test.msgpack | vd --filetype msgpack
```

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/threads.py", line 227, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/sheets.py", line 276, in reload
    self.loader()
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/sheets.py", line 301, in loader
    for r in self.iterload():
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/loaders/msgpack.py", line 19, in iterload
    yield from msgpack.unpackb(data, raw=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 177, in msgpack._cmsgpack.unpackb
  File "msgpack/_unpacker.pyx", line 125, in msgpack._cmsgpack.get_data_from_buffer
TypeError: a bytes-like object is required, not 'str'
```

This doesn't work:
```
> cat test.msgpackz | vd --filetype msgpackz
```

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/threads.py", line 227, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/sheets.py", line 276, in reload
    self.loader()
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/sheets.py", line 301, in loader
    for r in self.iterload():
  File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/loaders/msgpack.py", line 18, in iterload
    data = brotli.decompress(data)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

**Comment by maxim-uvarov** [comment]
While tests work ok:
```
> vd -p tests/load-msgpack.vd
saul.pw/VisiData v3.1dev
opening tests/load-msgpack.vd as vd

> vd -p tests/load-msgpackz.vd
saul.pw/VisiData v3.1dev
opening tests/load-msgpackz.vd as vd
```

**Comment by anjakefala** [comment]
Thanks @maxim-uvarov! I'm on it!

**Comment by anjakefala** [comment]
Hi @maxim-uvarov!

Once we merge, all of your cases as you outlined them should work!

One clarification is that you might need to specify the filetype for msgpackz: `vd test.msgpackz -f msgpackz`.

Thanks for helping us bring this together!

**Pull request merged**
