### PR TITLE
gatherBy() reports exceptions

### PR DESCRIPTION
**Pull request by frosencrantz**
Copying change from https://github.com/saulpw/visidata/commit/ad02b59b486ba2f2d4cf51c032d760a0ad661666

Could have helped with https://github.com/saulpw/visidata/issues/975

- [ ] If contributing a core loader, [the loader checklist](https://visidata.org/docs/contributing-to-visidata#loader) was referenced.
- [ ] If registering an external plugin, [the plugin checklist](https://visidata.org/docs/contributing-to-visidata#plugins) was referenced.

### CODE REVIEW

**Review by saulpw — COMMENTED** [review]
Hi @frosencrantz, did this help you debug something you were working on?  Generally I start with these except clauses calling `exceptionCaught`, and then remove them as they clutter the status line with even 'normal' errors.  So maybe there should be a `debug=` kwarg on exceptionCaught, which only displays a status message when options.debug is True, and/or a "silent" status message type which is not reported on the status line but does show up on the previous statuses sheet.

Again, I'm not opposed to the content of the change, but want to have a general solution to this class of problem.

**Comment by frosencrantz** [comment]
Hi @saulpw , I used it to debug https://github.com/saulpw/visidata/issues/975#issuecomment-835900045

I like your idea of providing a way to control the noise level of errors.  I do like seeing the most recent errors in the status message,  otherwise there would be issues I completely miss.

**Comment by saulpw** [comment]
Okay, with 6a56ee5, errors in this context will be shown on the status history sheet, but not on the status line.  Thanks for the impetus, @frosencrantz !

**Comment by frosencrantz** [comment]
Brilliant, @saulpw!  Thank you!  I think that would have made it easier to debug.

**Pull request closed without merging**
