### PR TITLE
[docs] add info about adding sorting to existing sort criteria

### PR DESCRIPTION
**Pull request by maxim-uvarov**
I added info about additional sorting criterias

### CODE REVIEW

**Review by saulpw — APPROVED** [review]
Thanks for adding this, @maxim-uvarov!  I'd like @anjakefala to review docs changes too, and then we can merge it.

**Comment by anjakefala** [comment]
Wonderful!! =)

**Comment by maxim-uvarov** [comment]
Guys, I've just found that the PRs to the develop branch don't get published on the site:
https://www.visidata.org/docs/columns/

Which branch should I make a PR to, to change the current site?

**Comment by anjakefala** [comment]
Hi @maxim-uvarov! We update the site when VisiData gets shipped, and merged to `stable`! The site then needs to be manually rebuilt. I will cherrypick your commit over first, and will rebuild ASAP.

**Pull request merged**
