### PR TITLE
added dialect agnostic DB loaders via SQLAlchemy, handles mysql and oracle

### PR DESCRIPTION
**Pull request by aswan89**
This code uses SQL Alchemy to load data from MySQL and Oracle databases via a supplied DBAPI URL.

A handler for MSSQL could likely be added quickly but I did not have ready access to a large MS SQL database to test against. 

The loader will first load available database schemas and will drill down into tables as they are selected.

### CODE REVIEW

**Comment by saulpw** [comment]
Thanks for pulling this together, @aswan89!  I'll take a close look at this over the weekend.

**Review by saulpw — COMMENTED** [review]
I think this would be great as a plugin in one of your own repos, @aswan89 !  Then you can maintain and release this code as you please, and we'll put an entry in the `plugins.jsonl` so people can install your code and its dependencies as they need.

**Comment by aswan89** [comment]
If the code would be better off living outside the core repo that's fine. I am seeing some conflicting info about how plugins work within the repository. 
 https://github.com/saulpw/visidata/blob/develop/dev/checklists/add-plugin.md vs.
https://github.com/saulpw/visidata/blob/develop/docs/plugins.md 

Is it as simple as me init-ing a new repo for my code with a requirements.txt for the additional dependencies and then opening a pull request to incorporate it to the core visidata repo somehow? You made reference to `plugins.json1` but I don't really see that in the repo or in the example plugin repos linked earlier.

**Comment by anjakefala** [comment]
Hey @aswan89!

I am sorry. That is confusing. We are currently still experimenting with what the plugin workflow is going to be. The [docs/plugins.md](https://github.com/saulpw/visidata/blob/develop/docs/plugins.md) that you found was a bit out-dated. I have been focussing on updating [dev/checklists/add-plugin.md](https://github.com/saulpw/visidata/blob/develop/dev/checklists/add-plugin.md). I just ensured both are more comprehensive, and updated.

The basic idea is that we want to distinguish which parts of the code core maintainers are going to take-on responsibility for bug-fixing, feature-completing, and keeping up to date. Loaders also tend to come up with additional dependencies, and we want to make it easier to install those dependencies only for the loaders that you are interested in using.

To make this into a loader, move it from `visidata/visidata/loaders/` into `visidata/plugins`. The `plugins.jsonl` should now be present on the `develop` branch in `visidata/plugins/plugins.jsonl`. You can write the dependencies into the `pydeps` section. 

@ajkerrigan developed a script for generating the sha256, if you need help with that: https://gist.github.com/ajkerrigan/7bd8f0c14543b7a78a68b71e95b8d5a1. I will take the responsibility of making sure it is correct and working, and making sure the urls are correct.

If you prefer to not have us as middlemen whenever you update your plugin, you can make a PR on plugins.jsonl, and just have its url section point to where you are hosting your plugin. =) Then others can freely install it, use it, and you can easily update it.

**Comment by saulpw** [comment]
Hi @aswan89 , thanks again for putting in the work on this!  We're still working out the exact process for plugins, and I'm sorry I didn't get to coordinate sooner.

I think it's best if it goes as a plugin into your own repo--and yes, the `.py` file is sufficient to get it working, though you'll also want a `README` and `LICENSE` so other people know how they can use it.  Then this PR becomes just the plugins.jsonl addition, with the url changed to point to your own repo.  I'd encourage you to formally 'release' it as v1 as it will make things easier to handle changes in the future.

**Review by saulpw — APPROVED** [review]
Okay, thanks @aswan89 !  This is great.  The pydeps should actually be separated by spaces, but we can take care of it this time.  Thanks for putting this together!

**Comment by aborruso** [comment]
Hi @aswan89 is there some README.md on how to use VD to access to Oracle db? What's the string to use?

Thank you, great thing!

**Comment by aswan89** [comment]
> 
> 
> Hi @aswan89 is there some README.md on how to use VD to access to Oracle db? What's the string to use?
> 
> Thank you, great thing!

The barebones readme is found in the [plugin repo](https://github.com/aswan89/visidata_plugin_genericSQL) but the short answer is to use an [SQLAlchemy friendly DB URL](https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls),

**Pull request merged**
