### PR TITLE
Fix resizing issue with wide chars (#279)

### PR DESCRIPTION
**Pull request by polm**
This fixes the issue with resizing described in #279. (And the PR is for the right branch this time!)

### CODE REVIEW

**Comment by anjakefala** [comment]
Thanks =D

**Comment by anjakefala** [comment]
Hey @polm! I tested your code out on benchmarks.csv and I cannot confirm the fix. Can you upload the sample data that you saw an improvement with?

**Comment by polm** [comment]
Here's the sample file I was using:

```
one,two,three
壱弐参四五六七八九拾,ok,test-test
this is a test,test two, test three
```

**Comment by anjakefala** [comment]
I can confirm that it works beautifully with benchmarks.csv as well. =) I was mistaken.

**Comment by anjakefala** [comment]
Code looks good. I am going to proceed to merge it in. If adjustments for styling are made, we will leave you a message here. =)

Thank you so much, @polm!

**Pull request merged**
