### PR TITLE
Added support for bam sequence alignment formats

### PR DESCRIPTION
**Pull request by soymintc**
Added a loader for bam format, which uses the [SAM/BAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf).
I've used a module called pysam for the loader.
Since I haven't registerd a plugin I've only checked the loader checklist box below.
- [x] If contributing a core loader, [the loader checklist](https://visidata.org/docs/contributing#loader) was referenced.
- [ ] If registering an external plugin, [the plugin checklist](https://visidata.org/docs/contributing#plugins) was referenced.

### CODE REVIEW

**Comment by anjakefala** [comment]
Test failure:

```
AttributeError
Traceback (most recent call last):
  File "/home/anja/git/visidata/visidata/utils.py", line 100, in __getattr__
    return self[self._fields.index(k)]
ValueError: 'sheet' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anja/git/visidata/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/anja/git/visidata/visidata/main.py", line 339, in vd_cli
    rc = main_vd()
  File "/home/anja/git/visidata/visidata/main.py", line 315, in main_vd
    if vd.replay_sync(vs):  # error
  File "/home/anja/git/visidata/visidata/cmdlog.py", line 368, in replay_sync
    vd.exceptionCaught(e)
  File "/home/anja/git/visidata/visidata/cmdlog.py", line 363, in replay_sync
    if vd.replayOne(cmdlog.cursorRow):
  File "/home/anja/git/visidata/visidata/cmdlog.py", line 308, in replayOne
    if r.sheet and longname not in ['set-option', 'unset-option']:
  File "/home/anja/git/visidata/visidata/utils.py", line 102, in __getattr__
    raise AttributeError
AttributeError
```

Turns out that that the `.vd` was a sample `.bam` golden, not the `.vd` itself. We should probably have a clearer error, if someone is trying to replay a file that is not a proper `.vd(j)`.

**Comment by soymintc** [comment]
Thanks for the fix @anjakefala, didn't know because couldn't find a manual about creating a `tests/*.vd` file. 
[1] Could you let me know of a manual to create the vd file? (so that I don't make the same error in future commits)
[2] What else could I do to merge the dev_bam to the develop or stable branch (then delete dev_bam)? I've checked that the dev_bam version visidata can open the bam file, which seems good enough for using it for my current purposes. Still, I'd like to upgrade the bam loader later so that it can edit bam files using visidata and save bam files instead of tsv files (as does the current dev_bam version)
[3] It would greatly help if I could find some other documents for development (preferences, formats... whatever), since while making the loader what I did was just try to fit the commit to the previous styles by basically eyeballing the git log files and see what others did. ;)

**Comment by anjakefala** [comment]
Oh gosh @soymintc! I just realised how my comment read. I was just getting this PR ready for @saulpw to review when he next allocates time for it. =) 

Thank you so much for making this PR! I used to do sequence alignment work, and this is a really neat addition to VisiData. Happy to see bioinformaticians engaging with it. <(^___^)> 

Your questions are really good insight for holes in our documentation.

>  [1] Could you let me know of a manual to create the vd file? (so that I don't make the same error in future commits)

It is hidden here: https://www.visidata.org/docs/save-restore/ and here https://jsvine.github.io/intro-to-visidata/advanced/the-command-log/

> Still, I'd like to upgrade the bam loader later so that it can edit bam files using visidata and save bam files instead of tsv files (as does the current dev_bam version)

Would a plugin be a better route to take? For plugins, you could develop the `bam` loader in your own repository, and then make a PR so that VisiData knows about your upgraded plugin: e.g. here: https://github.com/saulpw/visidata/pull/1119. Though, now the `plugins.jsonl` is hosted here: https://github.com/visidata/dlc/blob/stable/plugins.jsonl. So you would make a PR against this repo. I will make sure all of our documentation is clear about that.

It means there will likely be a shorter review process, and you could take responsibility for keeping it up to date and hosting issues. 

`Space` `open-plugins` in VisiData will open a **PluginsSheet** where users can install, activate and deactivate plugins. 

I would keep this PR as it is until @saulpw reviews it, though, and then you two can talk about what the best fit is, whether as a loader or a plugin. But worth thinking about.

> It would greatly help if I could find some other documents for development (preferences, formats... whatever), since while making the loader what I did was just try to fit the commit to the previous styles by basically eyeballing the git log files and see what others did. ;)

This is a pretty good approach! This is how I learned. =) The official documentation is here: https://www.visidata.org/docs/api/loaders. Did you know about this documentation? Did you find it accessible?

**Comment by soymintc** [comment]
No problem @anjakefala! Thanks for letting me me know, and for the detailed info as well! Really appreciate it :) 
Nice to hear that you have been doing alignment workl! I heard about this tool from a bioinformatician colleague; really big thanks for coming up with this awesome tool!

> Would a plugin be a better route to take? For plugins, you could develop the bam loader in your own repository, and then make a PR so that VisiData knows about your upgraded plugin: e.g. here: https://github.com/saulpw/visidata/pull/1119. 
Though, now the plugins.jsonl is hosted here: https://github.com/visidata/dlc/blob/stable/plugins.jsonl. So you would make a PR against this repo. I will make sure all of our documentation is clear about that.

Coming to think of it, yes, plugins seem to be the way to go for the bam-saving functionality, but let's check with @saulpw as you said.

> This is a pretty good approach! This is how I learned. =) The official documentation is here: https://www.visidata.org/docs/api/loaders. Did you know about this documentation? Did you find it accessible?

I found the [Loaders docs](https://www.visidata.org/docs/api/loaders) really accessible, because it was found right away when I googled "contribute to visidata", and helpful, because it was intuitive enough that I could figure out what the function name should be, what return values I have to give, etc! 
But as a total noob to this visidata world, I wasn't sure (and some still are not sure) of several stuff just by reading the docs itself. Examples are:
- when I should use `reload`
- why the Column docs suddenly appeared - had to read to the Full Example part of the docs to figure out why
- what files I have edit to run a new loader smoothly (e.g. didn't think of editing visidata/__init__.py before I got an error - my bad though)

**Comment by saulpw** [comment]
Hi @soymintc!  Thanks for putting this together.  I think that it's probably best to keep it as a plugin while you're still actively working on it, so you can develop and share it more quickly than the usual VisiData release cycle.  I'd love to help you on this.  Feel free to stop by IRC libera.chat #visidata or visidata.org/chat for the Discord and I'd be happy to provide guidance and answer any questions.

**Comment by soymintc** [comment]
Hi @saulpw :) Sounds great! Thanks for letting me know of the channels. When I get to the plugins stage I'm 100% sure I'd be asking tons of questions.

**Comment by anjakefala** [comment]
@soymintc Oh no! This PR became funky because some commits have not been merged back into `develop`, yet. I will try to clean that up.

**Comment by anjakefala** [comment]
@soymintc, I would undo your merge commit: https://github.com/saulpw/visidata/pull/1382/commits/fde6a1d4cf8f0ef22d38b22bfb6b7e7ba11b5dc3

And update from `develop`, instead. Everything is now merged into there. This will help fix the PR. Do you know how to undo a merge in `git`?

**Comment by soymintc** [comment]
@anjakefala Arrgh sorry about the merged-dev_bam push into my origin. Totally my bad. :sweat_smile: Reverted merge and pushed again. Please let me know if anything else should be fixed. 
Oh... by any chance do you want me to reset to previous commit and force push?

**Comment by anjakefala** [comment]
> Oh... by any chance do you want me to reset to previous commit and force push?

Yeah, that might be what needs to happen! Then update from `develop`. =)

**Comment by soymintc** [comment]
@anjakefala Gotcha 😃

**Comment by anjakefala** [comment]
@soymintc I made a cookiecutter template for creating plugins for VisiData =) https://github.com/visidata/visidata-plugin

**Comment by soymintc** [comment]
> @soymintc I made a cookiecutter template for creating plugins for VisiData =) https://github.com/visidata/visidata-plugin

@anjakefala Great news!! Really appreciate taking your time for it!

**Pull request closed without merging**
