### PR TITLE
[regex] Use capture names for column names, if available, in capture-col

### PR DESCRIPTION
**Pull request by tsibley**
Allows for predetermining friendlier column names, saving a renaming
step later.

### CODE REVIEW

**Comment by geekscrapy** [comment]
FYI, addresses #535 👍

**Comment by tsibley** [comment]
@geekscrapy Ah, thanks for that pointer. Glad I'm not the only one who wants this feature! :-)

I notice that in your plugin version the capture group names are used as-is. In this PR version, they're prefixed with the original column name. I went with the prefix because it paralleled the existing numbering behaviour (e.g. `col_re0`, `col_re1`, etc), but I know there will be times when I really don't want the original column name crufting things up. I didn't have any good ideas for how to parameterize that behaviour (other than with an additional command, which I didn't want to do), but maybe you or someone else does?

One idea I had but that I didn't like was to reverse the default (so no prefix by default) and then flag that you want a prefix by naming your captures with a leading underscore. But again, I think this is probably worse than just defaulting to a prefix with no way to change it.

**Comment by geekscrapy** [comment]
Yes that does keep inline I guess. Tbh, when I created that it was to scratch an itch I had so didn't think about it much.

My feeling is that it would be great to have the option of both (group names and extended col names) as you could potentially be creating a lot of columns with this.

On the flip side, if you know a way to mass rename columns this maybe isn't so much of an issue?

**Comment by saulpw** [comment]
Let's keep the prefix by default, especially as it's easier to take out than insert after-the-fact.  As @geekscrapy mentioned, columns can be mass renamed in the ColumnsSheet with e.g. `g*` which makes it easy enough to remove a prefix (though you do have to input the column name or fiddle with regex, so we could streamline that at some point--maybe with formally segmented column names).  So this is great @tsibley, thanks a lot for putting this together.

Where should we make a note of this in the user docs, @anjakefala?

**Comment by tsibley** [comment]
@saulpw Thanks! I've pushed [another PR](https://github.com/saulpw/visidata/pull/810) to note this in the docs. I should have done that the first time around! :-)

**Pull request merged**
